export const Translations = new Mongo.Collection('translations');

Translations.find().fetch().forEach((language) => {
  T9n.map(language._id, language.translations);
});

Meteor.publish('translations', function () {
  return Translations.find()
});

Translations.update({_id: 'ru'}, {$set: {'translations.landing.tabs.8.header': 'Преимущества', 'translations.landing.tabs.8.body': 'Данный сайт позволяет использовать для видеонаблюдения веб камеры, которые в несколько раз дешевле ip камер и других решений для видеонаблюдения, существующих на рынке. Кроме того для установки видеонаблюдения не нужно специальных знаний. Достаточно просто зайти в свой аккаунт с устройства с подключенной камерой, будь то компьютер, смартфон, телефон или планшет, и доступом в интернет, создать канал, выбрать камеру из доступных на устройтве, и просмотривать его с любого другого или с того же устройства со своего аккаунта. К компьютеру или другому устройству можно подключить несколько камер, используя usb хаб. Камеру можно установить в любом месте, проложив usb кабель. Ссылки на эти необходимые компоненты находятся в левом меню управления, которое доступно после регистрации и входа в аккаунт. Все эти компоненты имеют меньшую цену, чем те которые необходимы для установки ip камер. Для настройки системы не требуются специалисты или специальные знания. Пользователь также имеет возможность вести запись созданных каналов. Также есть возможность просмотра всех созданных каналов на странице мониторинг.'}});

Translations.update({_id: 'en'}, {$set: {'translations.landing.tabs.8.header': 'Advantages', 'translations.landing.tabs.8.body': "This site allows you to use web cameras for video surveillance, which are several times cheaper than ip cameras and other video surveillance solutions on the market. In addition, for the installation of video surveillance user does not need special knowledge. Simply access your account from a device with a connected camera, be it a computer, smartphone, phone or tablet, and internet access, create a channel, select a camera from those available on the device, and view it from any other device or from the same device using your account. You can connect multiple cameras to a computer or other device using a usb hub. The camera can be installed anywhere by laying usb cable. Links to these necessary components are in the left-hand management menu, which is available after registering and logging into your account. All these components have a lower price than those that are needed to install ip cameras. To configure the system user does not require specialists or special knowledge. The user also has the ability to record the created channels. It is also possible to view all created channels on the 'monitoring' page."}});

Translations.update({_id: 'uk'}, {$set: {'translations.landing.tabs.8.header': 'Переваги', 'translations.landing.tabs.8.body': "Даний сайт дозволяє використовувати для відеоспостереження веб камери, які в кілька разів дешевше ip камер і інших рішень для відеоспостереження, існуючих на ринку. Крім того для установки відеоспостереження не потрібно спеціальних знань. Досить просто зайти в свій аккаунт з пристрою з підключеною камерою, будь то комп'ютер, смартфон, телефон або планшет, і доступом в інтернет, створити канал, вибрати камеру з доступних на пристрої, і переглядати його з будь-якого іншого або з того ж пристрою зі свого аккаунта. До комп'ютера або іншого пристрою можна підключити декілька камер, використовуючи usb хаб. Камеру можна встановити в будь-якому місці, проклавши usb кабель. Посилання на ці необхідні компоненти знаходяться в лівому меню управління, яке доступне після реєстрації і входу в аккаунт. Всі ці компоненти мають меншу ціну, ніж ті які необхідні для установки ip камер. Для налаштування системи не потрібні фахівці або спеціальні знання. Користувач також має можливість вести запис створених каналів. Також є можливість перегляду всіх створених каналів на сторінці моніторинг."}});